### ISSUE TITLE
Propose updates to kubeadm-vagrant instructions

### ISSUE THREAD

**Issue by adrianparks** [scottslowe/learning-tools#120]
Running VirtualBox as my hypervisor (on CentOS 7.5), I've found that when the K8s VMs boot up and the services are installed, they bind to the first NIC (NAT connection to the outside world) rather than the second NIC (the 192.168.100.0/24 private network). This applies to all services except the API server, and broke networking for me (all nodes use the same IP address for the first NIC, and there is no connectivity on that network between nodes anyway). It's fixable by adding the `--node-ip` argument to the kubelet process at startup, telling it to bind to the second NIC - e.g.

        sed -i "s/KUBELET_EXTRA_ARGS=/KUBELET_EXTRA_ARGS=--node-ip=<correct-ip-address-here>/" /etc/default/kubelet

Also, even with the config changed to use the internal network, I couldn't get Calico v3 working by following step 9 - neither the Calico nor the CoreDNS pods would fire up. However, after installing v3.3 following instructions at https://docs.projectcalico.org/v3.3/getting-started/kubernetes/, all pods run fine.

I'm presuming this is the same with other providers, but haven't tested with them. If this is an acceptable solution, I'm happy to create a pull request to update the instruction steps as per the contribution guidelines, as that would also be a useful learning experience for me!

**Comment by scottslowe** [comment]
@adrianparks Thanks for testing with VirtualBox, and thanks for uncovering these errors. Happy to have you submit a PR with suggested changes. Thanks for being willing to contribute!

**Comment by adrianparks** [comment]
My pleasure - it's the least I can do. I really appreciate your taking the time to create this repository, it's proving extremely useful to me. So many thanks! PR now submitted (hopefully following the contribution guidelines correctly).

**Comment by scottslowe** [comment]
Thanks for the PR, merged!

Closed via #121.
