### ISSUE TITLE
[Enhancement / Suggestion] Add more resources under terraform/aws

### ISSUE THREAD

**Issue by UdhavPawar** [scottslowe/learning-tools#137]
Hey @scottslowe , loving all the content here 💯 

Have been working on couple of Terraform projects and digging around to find + learn from cool resources such as yours. Was going through the Terraform code for aws at `terraform/aws ` and figured we could possibly contribute more resources.  To name a few:
```
1. s3
2. elasticache
3. dynamodb
4. beanstalk
5. waf 
```

Let me know if such contribution will add value to the existing set of learning tools, if so I'll initiate a PR :)

Regards,
Udhav

**Comment by scottslowe** [comment]
@UdhavPawar I'd love to see more examples! A PR is very welcome. Anything that makes this repository more useful to folks is something I'll evaluate for inclusion. Thanks!

**Comment by UdhavPawar** [comment]
Awesome 👌  PR on the way
